config/routes.rb
# == Route Map
#
#                               Prefix Verb   URI Pattern                                                        Controller#Action
#                          attachinary        /attachinary                                                       Attachinary::Engine
#                     new_user_session GET    /users/sign_in(.:format)                                           devise/sessions#new
#                         user_session POST   /users/sign_in(.:format)                                           devise/sessions#create
#                 destroy_user_session DELETE /users/sign_out(.:format)                                          devise/sessions#destroy
#                    new_user_password GET    /users/password/new(.:format)                                      devise/passwords#new
#                   edit_user_password GET    /users/password/edit(.:format)                                     devise/passwords#edit
#                        user_password PATCH  /users/password(.:format)                                          devise/passwords#update
#                                      PUT    /users/password(.:format)                                          devise/passwords#update
#                                      POST   /users/password(.:format)                                          devise/passwords#create
#             cancel_user_registration GET    /users/cancel(.:format)                                            devise_invitable/registrations#cancel
#                new_user_registration GET    /users/sign_up(.:format)                                           devise_invitable/registrations#new
#               edit_user_registration GET    /users/edit(.:format)                                              devise_invitable/registrations#edit
#                    user_registration PATCH  /users(.:format)                                                   devise_invitable/registrations#update
#                                      PUT    /users(.:format)                                                   devise_invitable/registrations#update
#                                      DELETE /users(.:format)                                                   devise_invitable/registrations#destroy
#                                      POST   /users(.:format)                                                   devise_invitable/registrations#create
#               accept_user_invitation GET    /users/invitation/accept(.:format)                                 devise/invitations#edit
#               remove_user_invitation GET    /users/invitation/remove(.:format)                                 devise/invitations#destroy
#                  new_user_invitation GET    /users/invitation/new(.:format)                                    devise/invitations#new
#                      user_invitation PATCH  /users/invitation(.:format)                                        devise/invitations#update
#                                      PUT    /users/invitation(.:format)                                        devise/invitations#update
#                                      POST   /users/invitation(.:format)                                        devise/invitations#create
#                                 root GET    /                                                                  pages#home
#                       planning_slots POST   /plannings/:planning_id/slots(.:format)                            slots#create
#                    new_planning_slot GET    /plannings/:planning_id/slots/new(.:format)                        slots#new
#                   edit_planning_slot GET    /plannings/:planning_id/slots/:id/edit(.:format)                   slots#edit
#                        planning_slot GET    /plannings/:planning_id/slots/:id(.:format)                        slots#show
#                                      PATCH  /plannings/:planning_id/slots/:id(.:format)                        slots#update
#                                      PUT    /plannings/:planning_id/slots/:id(.:format)                        slots#update
#                                      DELETE /plannings/:planning_id/slots/:id(.:format)                        slots#destroy
#           planning_compute_solutions GET    /plannings/:planning_id/compute_solutions(.:format)                compute_solutions#index
#                                      POST   /plannings/:planning_id/compute_solutions(.:format)                compute_solutions#create
# change_effectivity_planning_solution GET    /plannings/:planning_id/solutions/:id/change_effectivity(.:format) solutions#change_effectivity
#                    planning_solution GET    /plannings/:planning_id/solutions/:id(.:format)                    solutions#show
#                      events_planning GET    /plannings/:id/events(.:format)                                    plannings#events
#                resultevents_planning GET    /plannings/:id/resultevents(.:format)                              plannings#resultevents
#                            plannings GET    /plannings(.:format)                                               plannings#index
#                                      POST   /plannings(.:format)                                               plannings#create
#                             planning GET    /plannings/:id(.:format)                                           plannings#show
#                                      PATCH  /plannings/:id(.:format)                                           plannings#update
#                                      PUT    /plannings/:id(.:format)                                           plannings#update
#                       planning_users GET    /plannings/:id/users(.:format)                                     plannings#users
#                    planning_skeleton GET    /plannings/:id/skeleton(.:format)                                  plannings#skeleton
#                   planning_conflicts GET    /plannings/:id/conflicts(.:format)                                 plannings#conflicts
#                                users GET    /users(.:format)                                                   users#index
#                                 user GET    /users/:id(.:format)                                               users#show
#                                roles GET    /roles(.:format)                                                   roles#index
#                                      POST   /roles(.:format)                                                   roles#create
#                             new_role GET    /roles/new(.:format)                                               roles#new
#                           user_infos GET    /users/:id/infos(.:format)                                         users#infos
#                          user_dispos GET    /users/:id/dispos(.:format)                                        users#dispos
#                          sidekiq_web        /sidekiq                                                           Sidekiq::Web
#                    letter_opener_web        /letter_opener                                                     LetterOpenerWeb::Engine
#
# Routes for Attachinary::Engine:
#   cors GET  /cors(.:format) attachinary/cors#show {:format=>/json/}
#
# Routes for LetterOpenerWeb::Engine:
# clear_letters DELETE /clear(.:format)                 letter_opener_web/letters#clear
# delete_letter DELETE /:id(.:format)                   letter_opener_web/letters#destroy
#       letters GET    /                                letter_opener_web/letters#index
#        letter GET    /:id(/:style)(.:format)          letter_opener_web/letters#show
#               GET    /:id/attachments/:file(.:format) letter_opener_web/letters#attachment
#

Rails.application.routes.draw do

  mount Attachinary::Engine => "/attachinary"
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :plannings, only: [:show, :index, :update, :create] do
    collection do
      get '/ical', to: 'plannings#ical', as: 'ical'
    end
    resources :slots, only: [:create, :edit, :show, :update, :resolve, :new, :destroy]
    resources :compute_solutions, only: [:index, :create]
    resources :solution_slots, only: [:edit, :update]
    resources :solutions, only: [:show] do
      member do
        get :change_effectivity
      end
    end
    member do
      get :events, format: :json
      get :resultevents, format: :json
    end
  end

  get 'plannings/:id/users', to: 'plannings#users', as: 'planning_users'
  get 'plannings/:id/skeleton', to: 'plannings#skeleton', as: 'planning_skeleton'
  get 'plannings/:id/conflicts', to: 'plannings#conflicts', as: 'planning_conflicts'
  get 'plannings/:planning_id/compute_solution/:compute_solution_id', to: 'compute_solutions#show_calculation_details', as: 'show_cs_details'
  get 'plannings/:id/use_template/:planning_id', to: 'plannings#use_template', as: 'planning_use_template'


  resources :users, only: [:index, :show, :create, :new, :update] do
    resources :constraints, only: [:new, :create, :edit, :update, :destroy]
    resources :role_users, only: [:new, :create, :edit, :update, :destroy]
  end
  resources :roles, only: [:index, :new, :create, :show, :edit, :update, :destroy]
  resources :colors, only: [:new, :create]
  get 'users/:id/infos', to: 'users#infos', as: 'user_infos'
  get 'users/:id/personnal_constraints', to: 'users#personnal_constraints', as: 'user_personnal_constraints'
  post 'users/user_invite', to: 'users#user_invite', as: "users_invite"
  get 'users/:id/reinvite', to: 'users#reinvite', as: "user_reinvite"
  get 'users/:id/personnal_c_and_wh', to: 'users#personnal_constraints_and_working_hours', as: "user_c_and_wh"
  resources :colors, only: [:new, :create]

app/controllers/compute_solutions_controller.rb
class ComputeSolutionsController < ApplicationController
  before_action :set_planning, only: [:index, :create, :show_calculation_details]
require 'uri'

  def index
    authorize @planning
    policy_scope(@planning.compute_solutions)
    @valid_compute_solutions = @planning.valid_compute_solutions
    @outdated_compute_solutions = @planning.outdated_compute_solutions
    @solution = @planning.solutions.chosen.first
    if !@planning.slots.count.positive?
      flash.now[:alert] = "#{view_context.link_to("Ajoutez des créneaux à votre planning",
      planning_skeleton_path(@planning))}"
    end
    flash.now[:alert] = "Sélectionnez une solution" if !@planning.solutions.chosen.exists?
  end

  def create
    compute_solution = ComputeSolution.create(planning_id: @planning.id)
    ComputePlanningSolutionsJob.perform_later(@planning, compute_solution)
    redirect_to planning_compute_solutions_path(@planning)
  end

  def show_calculation_details
    @compute_solution = ComputeSolution.find(params[:compute_solution_id])
    authorize @compute_solution
    @timestamps = @compute_solution.timestamps_algo
    @timestamps_details = @compute_solution.get_timestamps_details
    @timestamps_length = get_timestamps_length(@timestamps)
  end

  private

  def set_planning
    @planning = Planning.find(params[:planning_id])
  end

  def get_timestamps_length(timestamps)
    # from timestamps_algo, calculate length of each block
    i = 0
    timestamps_length = []
    timestamps.each do |timestamp|
      if i.positive?
        # if diff in seconds = 0
        if timestamp[1] - timestamps[i-1][1] == 0
          b = timestamp[1].strftime("%L").to_i - timestamps[i-1][1].strftime("%L").to_i
          length = b/1000
        else # more than 1 second time difference
          length =  timestamp[1] - @timestamps[i-1][1]
        end
      else
        length = 0
      end
      timestamps_length << length
      i += 1
    end
    timestamps_length
  end
end

app/helpers/compute_solution_helper.rb
module ComputeSolutionHelper

  def s_in_h(seconds)
    unless seconds.nil?
      [seconds / 3600, seconds / 60 % 60].map { |t| t.to_s.rjust(2,'0') }.join('h')
    end
  end

  def update_key_name_of_a_hash(associated_instance, hash_to_update, old_key, new_key)
    # replace old key by new key
    hash_to_update[new_name.to_s.to_sym] = p_nb_hours_roles.delete role_name.to_sym
    associated_instance.save!
  end

end

app/views/compute_solutions/_list_computed_solutions.erb
<div class="panel-group" id="accordion">
  <% computed_solutions.each do |computed_solution| %>
    <div class="panel panel-default">
      <div class="panel-heading sol-head" data-id="<%= computed_solution.id %>">
        <div class="panel-title" id="sol-list">
          <%= link_to show_cs_details_path(@planning, computed_solution) do %>
            <i class="fa fa-info" style="padding-right:5px; z-index: 10"></i>
          <% end %>
          <div class="sol-status label label-<%= computed_solution.ready? ? "success" : computed_solution.error? ? "danger" : "info" %>">
            <%= t("computed_solutionution.status.#{computed_solution.status}")%>
            <span class="badge badge-white">
              <%= computed_solution.nb_optimal_solutions %>
            </span> <br>
            <small><%= l computed_solution.created_at, format: :default_heure %></small>
          </div>
          <div class="compute-props">
            <div class="infos">
              <blockquote>
                <p>Planning</p>
                <footer>
                  <%= computed_solution.p_nb_slots %> créneaux (<%= computed_solution.p_nb_hours %>heures)
                  <ul>
                    <% computed_solution.p_nb_hours_roles.each do |role_id_symbol, hours|%>
                      <% role = Role.find(role_id_symbol) %>
                      <li><span class="role-name" style="background-color:<%= role.color.hexadecimal_code %>; color: <%= role.color.dark?? "#f2f2f2" : "black" %>"> <%= role.name %></span> : <%= hours %>h</li>
                    <% end %>
                  </ul>
                </footer>
              </blockquote>
            </div>
            <div class="infos">
              <blockquote>
                <p>Users</p>
                <footer>
                  <%= computed_solution.team.values.flatten.uniq.count %> équipiers :
                  <ul>
                    <% computed_solution.team.each do |role_id_symbol, team| %>
                    <% role = Role.find(role_id_symbol.to_s.to_i) %>
                    <li> <span class="role-name" style="background-color:<%= role.color.hexadecimal_code %>; color: <%= role.color.dark?? "#f2f2f2" : "black" %>"> <%= role.name %></span> :
                      <%= team.join(", ") %>
                    </li>
                    <% end %>
                  </ul>
                </footer>
              </blockquote>
            </div>
            <div class="infos">
              <blockquote>
                <p>Solutions</p>
                <footer>
                  <%= computed_solution.nb_optimal_solutions %> bonnes solutions
                  <ul>
                    <li>combinaisons : <%= computed_solution.nb_possibilities_theory %></li>
                    <li>itérations : <%= computed_solution.nb_iterations %></li>
                    <li>solutions proches : <%= computed_solution.nb_solutions %></li>
                  </ul>
                </footer>
              </blockquote>
            </div>
          </div>
          <% if computed_solution.pending? %>
            <div><i class="fa fa-spinner fa-pulse"></i></div>
          <% end %>
        </div>
      </div>

      <div id="<%= computed_solution.id %>" class="panel-collapse collapse">
        <div class="panel-body">
          <div class="list-group">
            <% computed_solution.solutions.each_with_index do |solution, index| %>
              <div class="list-group-item sol-item <%= "chosen" if solution.chosen? %>">
                <div class="sol-status label label-caplan">#<%= index + 1 %></div>
                <div class="sol-details">
                  <% unless solution.grade.nil? %>
                  <strong>Note: <span class="badge badge-red"><%= solution.grade %></span></strong>
                  <% end %>
                  <strong> Indice de pertinence <span class="badge badge-blue" ><%= solution.relevance %></span></strong>
                  <% unless (solution.nb_conflicts.nil? || solution.nb_conflicts.zero?)  %>
                    <span class="badge badge-orange"> <%= pluralize(solution.nb_conflicts, "créneau vide", "créneaux vides") %></span>
                  <% end %>
                  <span class="badge badge-blue">
                    extra/under hours : <%= s_in_h(solution.nb_extra_hours) %> / <%= s_in_h(solution.nb_under_hours) %>
                  </span>
                  <% @employees_nb_days = solution.employees_nb_days %>
                  <% solution.employees_overtime.each do |e, s| %>
                    <% if e != 'No solution' %>
                    <%= e %> (<%= s > 0 ? "extra #{s_in_h(s)}" : "manque #{s_in_h(-s)}" %> en <%= @employees_nb_days[e.downcase] %> jours)
                    <% else  %>
                    <span class="badge badge-orange">
                      <%= "heures non allouées =  #{s_in_h(-s)}" %>
                    </span>
                      <% end  %>
                  <% end %>
                </div>
                <div class="action-group">
                    <%= link_to change_effectivity_planning_solution_path(id: solution) do %>
                      <% if solution.chosen? %>
                        <i class="fa fa-check-circle"></i>
                      <% else %>
                        <i class="fa fa-circle-o"></i>
                      <% end %>
                    <% end %>
                    <%= link_to planning_solution_path(id: solution) do %>
                      <i class="fa fa-eye"></i>
                    <% end %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/compute_solutions/_list_computed_solutions.html.erb
<div class="panel-group" id="accordion">
  <% computed_solutions.each do |computed_solution| %>
    <div class="panel panel-default">
      <div class="panel-heading sol-head" data-id="<%= computed_solution.id %>">
        <div class="panel-title" id="sol-list">
          <%= link_to show_cs_details_path(@planning, computed_solution) do %>
            <i class="fa fa-info" style="padding-right:5px; z-index: 10"></i>
          <% end %>
          <div class="sol-status label label-<%= computed_solution.ready? ? "success" : computed_solution.error? ? "danger" : "info" %>">
            <%= t("computed_solutionution.status.#{computed_solution.status}")%>
            <span class="badge badge-white">
              <%= computed_solution.nb_optimal_solutions %>
            </span> <br>
            <small><%= l computed_solution.created_at, format: :default_heure %></small>
          </div>
          <div class="compute-props">
            <div class="infos">
              <blockquote>
                <p>Planning</p>
                <footer>
                  <%= computed_solution.p_nb_slots %> créneaux (<%= computed_solution.p_nb_hours %>heures)
                  <ul>
                    <% computed_solution.p_nb_hours_roles.each do |role_id_symbol, hours|%>
                      <% role = Role.find(role_id_symbol) %>
                      <li><span class="role-name" style="background-color:<%= role.color.hexadecimal_code %>; color: <%= role.color.dark?? "#f2f2f2" : "black" %>"> <%= role.name %></span> : <%= hours %>h</li>
                    <% end %>
                  </ul>
                </footer>
              </blockquote>
            </div>
            <div class="infos">
              <blockquote>
                <p>Users</p>
                <footer>
                  <%= computed_solution.team.values.flatten.uniq.count %> équipiers :
                  <ul>
                    <% computed_solution.team.each do |role_id_symbol, team| %>
                    <% role = Role.find(role_id_symbol.to_s.to_i) %>
                    <li> <span class="role-name" style="background-color:<%= role.color.hexadecimal_code %>; color: <%= role.color.dark?? "#f2f2f2" : "black" %>"> <%= role.name %></span> :
                      <%= team.join(", ") %>
                    </li>
                    <% end %>
                  </ul>
                </footer>
              </blockquote>
            </div>
            <div class="infos">
              <blockquote>
                <p>Solutions</p>
                <footer>
                  <%= computed_solution.nb_optimal_solutions %> bonnes solutions
                  <ul>
                    <li>combinaisons : <%= computed_solution.nb_possibilities_theory %></li>
                    <li>itérations : <%= computed_solution.nb_iterations %></li>
                    <li>nb total solutions : <%= computed_solution.nb_solutions %></li>
                  </ul>
                </footer>
              </blockquote>
            </div>
          </div>
          <% if computed_solution.pending? %>
            <div><i class="fa fa-spinner fa-pulse"></i></div>
          <% end %>
        </div>
      </div>

      <div id="<%= computed_solution.id %>" class="panel-collapse collapse">
        <div class="panel-body">
          <div class="list-group">
            <% computed_solution.solutions.each_with_index do |solution, index| %>
              <div class="list-group-item sol-item <%= "chosen" if solution.chosen? %>">
                <div class="sol-status label label-caplan">#<%= index + 1 %></div>
                <div class="sol-details">
                  <% unless solution.grade.nil? %>
                  <strong>Note: <span class="badge badge-red"><%= solution.grade %></span></strong>
                  <% end %>
                  <strong> Indice de pertinence <span class="badge badge-blue" ><%= solution.relevance %></span></strong>
                  <% unless (solution.nb_conflicts.nil? || solution.nb_conflicts.zero?)  %>
                    <span class="badge badge-orange"> <%= pluralize(solution.nb_conflicts, "créneau vide", "créneaux vides") %></span>
                  <% end %>
                  <span class="badge badge-blue">
                    extra/under hours : <%= s_in_h(solution.nb_extra_hours) %> / <%= s_in_h(solution.nb_under_hours) %>
                  </span>
                  <% @employees_nb_days = solution.employees_nb_days %>
                  <% solution.employees_overtime.each do |e, s| %>
                    <% if e != 'No solution' %>
                    <%= e %> (<%= s > 0 ? "extra #{s_in_h(s)}" : "manque #{s_in_h(-s)}" %> en <%= @employees_nb_days[e.downcase] %> jours)
                    <% else  %>
                    <span class="badge badge-orange">
                      <%= "heures non allouées =  #{s_in_h(-s)}" %>
                    </span>
                      <% end  %>
                  <% end %>
                </div>
                <div class="action-group">
                    <%= link_to change_effectivity_planning_solution_path(id: solution) do %>
                      <% if solution.chosen? %>
                        <i class="fa fa-check-circle"></i>
                      <% else %>
                        <i class="fa fa-circle-o"></i>
                      <% end %>
                    <% end %>
                    <%= link_to planning_solution_path(id: solution) do %>
                      <i class="fa fa-eye"></i>
                    <% end %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/compute_solutions/index.html.erb
<%= render 'shared/planningsteps', locals: {planning: @planning, url: @url} %>

<div class="wrap-plan">
  <%= render partial: 'list_computed_solutions', locals: {computed_solutions: @valid_compute_solutions} %>
</div>
<div class="history">
  <h3>Historique de calcul</h3>
  <%= render partial: 'list_computed_solutions', locals: {computed_solutions: @outdated_compute_solutions} %>
</div>

app/views/compute_solutions/show_calculation_details.html.erb
<%= link_to "Retour aux solutions", planning_compute_solutions_path(@planning), { :class=>"btn-success" } %>

<div class="row">
  <div class="col-xs-6">
    <h3> <b>Number of possibilities - theory : </b><%= @compute_solution.nb_possibilities_theory %></h3>
    <% if @compute_solution.nb_iterations.nil? %>
      <h3>Number of iterations, number of cuts within tree, %tree covered ==> <b>Unable to calculate</b></h3>
    <% else %>
      <h3>Number of iterations : <%= @compute_solution.nb_iterations %></h3>
      <h3>Number of cuts within tree : <%= @compute_solution.nb_cuts_within_tree %></h3>
      <h3>%tree covered : <%= number_to_percentage((@compute_solution.nb_iterations.to_f / @compute_solution.nb_possibilities_theory)*100, precision: 2) %></h3>
    <% end %>
  </div>

  <div class="col-xs-6">
    <div id="chart"></div>
  </div>

  <div class="col-xs-12">
    <div id="table_div"></div>
  </div>

</div>

<%= javascript_include_tag "dataviz/calculation_details" %>
<%= content_for(:after_js) do %>

  <script>
    var t1 = <%= @timestamps_length[0] if @timestamps.length.positive? %>;
    var t2 = <%= @timestamps_length[1] if @timestamps.length > 1 %>;
    var t3 = <%= @timestamps_length[2] if @timestamps.length > 2%>;
    var t4 = <%= @timestamps_length[3] if @timestamps.length > 3%>;
    var t5 = <%= @timestamps_length[4] if @timestamps.length > 4 %>;
    var t6 = <%= @timestamps_length[5] if @timestamps.length > 5 %>;
    var t7 = <%= @timestamps_length[6] if @timestamps.length > 6 %>;
    var row1 = ['create ComputeSolution', '' , "<%= @timestamps_details[0][0] %>", 0, 0, 0];
    var row2 = ['start CreateSlotgroupsService','ComputeSolution creation', "<%= @timestamps_details[1][0]%>", <%= @timestamps_details[1][1] %>,<%= @timestamps_details[1][2] %>, <%=  @timestamps_details[1][3]%> ];
    var row3 = ['end CreateSlotgroupsService', 'Initialisation algo', "<%= @timestamps_details[2][0]%>", <%= @timestamps_details[2][1] %>,<%= @timestamps_details[2][2] %>, <%=  @timestamps_details[2][3]%> ];
    var row4 = ['start GoFindSolutionsService', 'Choix algo yes/no', "<%= @timestamps_details[3][0]%>", <%= @timestamps_details[3][1] %>,<%= @timestamps_details[3][2] %>, <%=  @timestamps_details[3][3]%> ];
    var row5 = ['start pick_best_solution', 'Balayage Arbre', "<%= @timestamps_details[4][0]%>", <%= @timestamps_details[4][1] %>,<%= @timestamps_details[4][2] %>, <%=  @timestamps_details[4][3]%> ];
    var row6 = ['start SaveSolutionsAndSolutionSlotsService', 'Tri des solutions', "<%= @timestamps_details[5][0]%>", <%= @timestamps_details[5][1] %>,<%= @timestamps_details[5][2] %>, <%=  @timestamps_details[5][3]%> ];
    var row7 = ['end SaveSolutionsAndSolutionSlotsService', 'Stockage solutions', "<%= @timestamps_details[6][0]%>", <%= @timestamps_details[6][1] %>,<%= @timestamps_details[6][2] %>, <%=  @timestamps_details[6][3]%> ];

  </script>
<% end %>