config/routes.rb
# == Route Map
#
#                               Prefix Verb   URI Pattern                                                        Controller#Action
#                          attachinary        /attachinary                                                       Attachinary::Engine
#                     new_user_session GET    /users/sign_in(.:format)                                           devise/sessions#new
#                         user_session POST   /users/sign_in(.:format)                                           devise/sessions#create
#                 destroy_user_session DELETE /users/sign_out(.:format)                                          devise/sessions#destroy
#                    new_user_password GET    /users/password/new(.:format)                                      devise/passwords#new
#                   edit_user_password GET    /users/password/edit(.:format)                                     devise/passwords#edit
#                        user_password PATCH  /users/password(.:format)                                          devise/passwords#update
#                                      PUT    /users/password(.:format)                                          devise/passwords#update
#                                      POST   /users/password(.:format)                                          devise/passwords#create
#             cancel_user_registration GET    /users/cancel(.:format)                                            devise_invitable/registrations#cancel
#                new_user_registration GET    /users/sign_up(.:format)                                           devise_invitable/registrations#new
#               edit_user_registration GET    /users/edit(.:format)                                              devise_invitable/registrations#edit
#                    user_registration PATCH  /users(.:format)                                                   devise_invitable/registrations#update
#                                      PUT    /users(.:format)                                                   devise_invitable/registrations#update
#                                      DELETE /users(.:format)                                                   devise_invitable/registrations#destroy
#                                      POST   /users(.:format)                                                   devise_invitable/registrations#create
#               accept_user_invitation GET    /users/invitation/accept(.:format)                                 devise/invitations#edit
#               remove_user_invitation GET    /users/invitation/remove(.:format)                                 devise/invitations#destroy
#                  new_user_invitation GET    /users/invitation/new(.:format)                                    devise/invitations#new
#                      user_invitation PATCH  /users/invitation(.:format)                                        devise/invitations#update
#                                      PUT    /users/invitation(.:format)                                        devise/invitations#update
#                                      POST   /users/invitation(.:format)                                        devise/invitations#create
#                                 root GET    /                                                                  pages#home
#                       planning_slots POST   /plannings/:planning_id/slots(.:format)                            slots#create
#                    new_planning_slot GET    /plannings/:planning_id/slots/new(.:format)                        slots#new
#                   edit_planning_slot GET    /plannings/:planning_id/slots/:id/edit(.:format)                   slots#edit
#                        planning_slot GET    /plannings/:planning_id/slots/:id(.:format)                        slots#show
#                                      PATCH  /plannings/:planning_id/slots/:id(.:format)                        slots#update
#                                      PUT    /plannings/:planning_id/slots/:id(.:format)                        slots#update
#                                      DELETE /plannings/:planning_id/slots/:id(.:format)                        slots#destroy
#           planning_compute_solutions GET    /plannings/:planning_id/compute_solutions(.:format)                compute_solutions#index
#                                      POST   /plannings/:planning_id/compute_solutions(.:format)                compute_solutions#create
# change_effectivity_planning_solution GET    /plannings/:planning_id/solutions/:id/change_effectivity(.:format) solutions#change_effectivity
#                    planning_solution GET    /plannings/:planning_id/solutions/:id(.:format)                    solutions#show
#                      events_planning GET    /plannings/:id/events(.:format)                                    plannings#events
#                resultevents_planning GET    /plannings/:id/resultevents(.:format)                              plannings#resultevents
#                            plannings GET    /plannings(.:format)                                               plannings#index
#                                      POST   /plannings(.:format)                                               plannings#create
#                             planning GET    /plannings/:id(.:format)                                           plannings#show
#                                      PATCH  /plannings/:id(.:format)                                           plannings#update
#                                      PUT    /plannings/:id(.:format)                                           plannings#update
#                       planning_users GET    /plannings/:id/users(.:format)                                     plannings#users
#                    planning_skeleton GET    /plannings/:id/skeleton(.:format)                                  plannings#skeleton
#                   planning_conflicts GET    /plannings/:id/conflicts(.:format)                                 plannings#conflicts
#                                users GET    /users(.:format)                                                   users#index
#                                 user GET    /users/:id(.:format)                                               users#show
#                                roles GET    /roles(.:format)                                                   roles#index
#                                      POST   /roles(.:format)                                                   roles#create
#                             new_role GET    /roles/new(.:format)                                               roles#new
#                           user_infos GET    /users/:id/infos(.:format)                                         users#infos
#                          user_dispos GET    /users/:id/dispos(.:format)                                        users#dispos
#                          sidekiq_web        /sidekiq                                                           Sidekiq::Web
#                    letter_opener_web        /letter_opener                                                     LetterOpenerWeb::Engine
#
# Routes for Attachinary::Engine:
#   cors GET  /cors(.:format) attachinary/cors#show {:format=>/json/}
#
# Routes for LetterOpenerWeb::Engine:
# clear_letters DELETE /clear(.:format)                 letter_opener_web/letters#clear
# delete_letter DELETE /:id(.:format)                   letter_opener_web/letters#destroy
#       letters GET    /                                letter_opener_web/letters#index
#        letter GET    /:id(/:style)(.:format)          letter_opener_web/letters#show
#               GET    /:id/attachments/:file(.:format) letter_opener_web/letters#attachment
#

Rails.application.routes.draw do

  mount Attachinary::Engine => "/attachinary"
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :plannings, only: [:show, :index, :update, :create] do
    collection do
      get '/ical', to: 'plannings#ical', as: 'ical'
    end
    resources :slots, only: [:create, :edit, :show, :update, :resolve, :new, :destroy]
    resources :compute_solutions, only: [:index, :create]
    resources :solution_slots, only: [:edit, :update]
    resources :solutions, only: [:show] do
      member do
        get :change_effectivity
      end
    end
    member do
      get :events, format: :json
      get :resultevents, format: :json
    end
  end

  get 'plannings/:id/users', to: 'plannings#users', as: 'planning_users'
  get 'plannings/:id/skeleton', to: 'plannings#skeleton', as: 'planning_skeleton'
  get 'plannings/:id/conflicts', to: 'plannings#conflicts', as: 'planning_conflicts'
  get 'plannings/:planning_id/compute_solution/:compute_solution_id', to: 'compute_solutions#show_calculation_details', as: 'show_cs_details'
  get 'plannings/:id/use_template/:planning_id', to: 'plannings#use_template', as: 'planning_use_template'


  resources :users, only: [:index, :show, :create, :new, :update] do
    resources :constraints, only: [:new, :create, :edit, :update, :destroy]
    resources :role_users, only: [:new, :create, :edit, :update, :destroy]
  end
  resources :roles, only: [:index, :new, :create, :show, :edit, :update, :destroy]
  resources :colors, only: [:new, :create]
  get 'users/:id/infos', to: 'users#infos', as: 'user_infos'
  get 'users/:id/personnal_constraints', to: 'users#personnal_constraints', as: 'user_personnal_constraints'
  post 'users/user_invite', to: 'users#user_invite', as: "users_invite"
  get 'users/:id/reinvite', to: 'users#reinvite', as: "user_reinvite"
  get 'users/:id/personnal_c_and_wh', to: 'users#personnal_constraints_and_working_hours', as: "user_c_and_wh"
  resources :colors, only: [:new, :create]

app/models/color.rb
# == Schema Information
#
# Table name: colors
#
#  id               :integer          not null, primary key
#  name_fr          :text
#  name_eng         :text
#  hexadecimal_code :text
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#

class Color < ApplicationRecord
  has_many :roles

  def brightness
    rgb = hexadecimal_code.gsub("#", "").scan(/../).map {|color| color.hex}
    Math.sqrt(
      0.299 * rgb[0]**2 +
      0.587 * rgb[1]**2 +
      0.114 * rgb[2]**2
    )
  end

  def dark?
    brightness < 150
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController


  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
  end


  private

  def user_params
    params.require(:user).permit(:first_name)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :infos, :dispos, :reinvite, :update]

  def index
    @users = policy_scope(User)
    authorize @users
  end

  # rubocop:disable AbcSize, MethodLength
  def show
    authorize @user
    @constraints = @user.constraints
    @constraint_categories = Constraint.categories
    @constraints_array = get_constraints_array(@constraints)
    @role_user = RoleUser.new
    @constraint = Constraint.new
    @unallocated_roles = Role.all - @user.roles
    respond_to do |format|
      format.js
      format.html
    end
  end
  # rubocop:enable AbcSize, MethodLength

  def infos
  end

  # rubocop:disable AbcSize, MethodLength
  def dispos
    @planning = Planning.first
    @constraints = @user.constraints
    @constraints_array =  get_constraints_array(@constraints)
  end
  # rubocop:enable AbcSize, MethodLength

  def new
    @user = User.new
    authorize @user
    @roles = Role.all
  end

  def user_invite
    @user = User.new(user_params)
      # raise
    authorize @user
    @roles = Role.all
    @user.password = Devise.friendly_token.first(8)
    if @user.valid?
      @user.save
      User.invite!(email: @user.email)
      # u.update(profile_picture: photo_params[:profile_picture]) if !photo_params[:profile_picture].nil?
      redirect_to users_path, notice: "#{@user.first_name} fait partie de votre entreprise"
    else
      render :new, user: @user, roles: @roles
    end
  end

  def reinvite
    if @user.invitation_token.nil?
      @user.invitation_token = "provional"
      @user.save
    end
    User.invite!(email: @user.email)
    redirect_to users_path, notice: "Une Nième invitation a été envoyée à #{@user.first_name} !"
  end

  def update
    # update working hours only
    authorize @user
    if params[:user].keys[0] == "working_hours"
      if @user.update(user_params)
        redirect_to user_path(@user)
      end
      # update profile_picture only
      elsif @user.update(photo_params)
        redirect_to user_path(@user)
      # update more items
      elsif @user.update(user_params)
        redirect_to user_path(@user)
      else
        render :edit, {ressource: @user}
    end
  end

  private

  def user_params
    params.require(:user).permit(policy(User).permitted_attributes)
  end

  def photo_params
    params.require(:user).permit(policy(@user).permitted_attributes)
  end

  def set_title
    ['Congé  annuel', 'Congé maladie', 'Préférence'].sample
  end

  def constraint_color(category)
    if category == :conge_annuel.to_s
      'blue'
    elsif category == :maladie.to_s
      'red'
    else
      'orange'
    end
  end

  def get_constraints_array(constraints)
    array = []
    constraints.each do |constraint|
      a = {
        id:  constraint.id,
        start:  constraint.start_at,
        end: constraint.end_at,
        title: constraint.category,
        created_at: constraint.created_at,
        updated_at: constraint.updated_at,
        color: constraint_color(constraint.category),
        user_id: constraint.user_id
      }
      array << a
    end
    array
  end

  def set_user
    @user = User.find(params[:id])
  end

end

app/helpers/user_helper.rb
module UserHelper
  def avatar_with_border_color(user)
    color = user.roles[0].color.hexadecimal_code if user.roles.any?
    color ||= 'black'
    options = { class: 'user-avatar-index', style: "border: solid 6px #{color}" }

    if user.profile_picture?
      cl_image_tag user.profile_picture.path, options
    else
      image_tag 'https://placehold.it/30x30', options
    end
  end

  def profile_picture(user, size = "")
    avatar = (size == "small")? 'avatar-small' : 'avatar'
    if user.profile_picture?
      cl_image_tag user.profile_picture.path, class: avatar
    else
      image_tag 'https://placehold.it/30x30', class: avatar
    end
  end

  def invitation_status(user)
    if !user.invitation_accepted_at.nil?
      "green"
    elsif !user.invitation_sent_at.nil?
      "orange"
    end
  end

end

app/views/users/_ajax_constraints_cal.html.erb
<div id = "calendar">
</div>

<%= javascript_include_tag "components/calendar" %>
<script>
  var events = <%= raw @constraints_array.to_json %> ;
  var defaultDate = "<%= Date.today %>" ;
  displayCalendar(events, defaultDate);
</script>

app/views/users/_constraint_form.html.erb
<%= simple_form_for [@user], :url => user_constraints_path(@user), :method => :post do |f| %>
  <%= f.error_notification %>
  <div class="row">
    <div class="col-xs-12">
      <div class="form-group dates-input">
        <div class='input-group date' id='datetimepicker1'>
          <input name="constraint[start_at]" type='text' class="form-control" />
          <span class="input-group-addon">
            <span class="glyphicon glyphicon-calendar">
            </span>
          </span>
        </div>
      </div>
      <div class="form-group dates-input">
        <div class='input-group date' id='datetimepicker2'>
          <input name="constraint[end_at]" type='text'  class="form-control" />
          <span class="input-group-addon">
            <span class="glyphicon glyphicon-calendar">
            </span>
          </span>
        </div>
      </div>
    </div>
  </div>
  <div class="form-group">
    <ul class="list-inline categories">
      <% @constraint_categories.each do |type, number| %>
      <li>
        <div class="daysbox col-xs-3 category" id=<%= number %>>
          <label>
            <%= type %>
            <%= radio_button_tag "category[]", number, false, class: "hide", required: true %>
          </label>
        </div>
      </li>
      <% end %>
    </ul>
  </div>
  <div class="row days-list">
    <div class="col-xs-12">
      <div class="form-group">
        <ul class="list-inline" >
          <% [1,2,3,4,5,6].each do |daynum| %>
            <li>
              <div class="daysbox col-xs-4">
                <label>
                <%= t("days.#{Date::DAYNAMES[daynum]}") %>
                <%= check_box_tag "items[]", daynum, false, class: "hide" %>
                </label>
              </div>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12">
      <div class="form-group button-group">
          <%= f.submit "Valider", class: "mybtn mybtn--medium create_constraint", format: :js, :html => {:remote => true } %>
          <%= f.button :button, "Modifier", type: :reset, class: "mybtn mybtn--medium update_constraint" %>
          <%= f.button :button, "Cancel", type: :reset, class: "mybtn mybtn--medium cancel-button" %>
          <%= f.button :button, "Supprimer", type: :reset, class: "mybtn mybtn--medium delete_constraint" %>

      </div>
    </div>
  </div>
<% end %>

app/views/users/_edit_working_hours.html.erb
<%= simple_form_for(@user) do |f| %>
  <%= f.error_notification %>
  <%= f.input :working_hours, label: false, required: true, input_html: { class: "hide" }  %>
  <%= f.input :email, label: false, required: true, input_html: { class: "hide" } %>
  <%= f.input :first_name, label: false, required: true, input_html: { class: "hide" } %>
  <%= f.input :last_name, label: false, required: true, input_html: { class: "hide" } %>

  <div class="row">
    <div class="col-xs-12">
      <div class="form-group button-group">
          <%= f.submit "Valider", class: "mybtn mybtn--medium"%>
      </div>
    </div>
  </div>
<% end %>

app/views/users/_form_profile_picture.html.erb
<%= simple_form_for(resource, as: resource_name ) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">

    <% if devise_mapping.confirmable? && resource.pending_reconfirmation? %>
      <p>Currently waiting confirmation for: <%= resource.unconfirmed_email %></p>
    <% end %>

    <label class="custom-file-upload">
      <span class="custom-file-upload-btn">
        <i class="fa fa-cloud-upload"></i> Votre avatar
      </span>
      <%= f.input :profile_picture, as: :attachinary, placeholder: "chemin image", label: false %>
    </label>
  </div>

  <div class="form-actions">
    <%= f.submit "Valider", class: "btn btn-success" %>
  </div>
<% end %>

app/views/users/_html_constraints_cal.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-2 flex-col">
    <h3>Actions</h3>
    <button class="mybtn mybtn--small show_working_hours">Horaires de travail</button>
  </div>
  <div class="col-xs-12 col-sm-10 le_calendrier">
    <div id = "calendar">
    </div>
  </div>
</div>



<%= javascript_include_tag "components/calendar-constraints" %>
<%= content_for(:after_js) do %>
  <script>

    var events_constraints_and_wh = '<%= user_c_and_wh_path(@user, format: :json) %>';
    var defaultDate = "<%= Date.today %>" ;
    var user_id = "<%= @user.id %>" ;

    modifyConstraintsCalendar(events_constraints_and_wh, defaultDate, user_id);
    hidestuff();
  </script>
<% end %>

app/views/users/_modal.html.erb
<div class="modal fade modal-user" tabindex="-1" role="dialog"
 aria-labelledby="myModalLabel" aria-hidden="true" id="userModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <!-- Modal Header -->
      <div class="modal-header">
        <button type="button" class="close"
        data-dismiss="modal">
          <span aria-hidden="true">&times;</span>
          <span class="sr-only">Close</span>
        </button>
        <h4 class="modal-title" id="myModalLabel">
          <strong>Les infos de <%= @user.first_name.capitalize %></strong>
        </h4>
      </div>

    <!-- Modal Body -->
      <div class="modal-body">
        <%= render "user_infos" %>
        <%= render 'ajax_constraints_cal' %>
      </div>
    </div>
  </div>
</div>

app/views/users/_user_infos.html.erb
<div>
  <ul class="metier-list list-inline">
    <% @user.roles.each do |role| %>
      <li class="mr+" style="background-color: <%=  role.color.hexadecimal_code %>; color: <%= role.color.dark?? "#f2f2f2" : "black" %>"> <%= role.name.capitalize %>
      </li>
      <% if current_user.is_owner %>
        <i class="fa fa-minus-square delete-role <%= "user"+@user.id.to_s %> <%= "roleuser"+RoleUser.find_by(user_id: @user.id, role_id: role.id).id.to_s %> <%= "role"+role.id.to_s %> pointer mr+ fa_with_bg" aria-hidden="true">
        </i>
      <% end %>
    <% end %>
      <% if @user.roles.count != Role.all.count && current_user.is_owner %>
        <i class="fa fa-plus-square fa_with_bg pointer mr-" aria-hidden="true"></i>
      <% end %>
  </ul>
</div>

<div class="modal fade modal-role-user modal-events" tabindex="-1" role="dialog">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      <h4 class="modal-title">Ajouter un rôle</h4>
    </div>
    <div class="modal-body">
        <%= render 'role_users/form', user: @user%>
    </div>
  </div>
</div>

<div class="modal fade modal-edit-working-hours modal-events" tabindex="-1" role="dialog">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      <h4 class="modal-title">Modifier</h4>
    </div>
    <div class="modal-body">
        <%= render 'users/edit_working_hours' %>
    </div>
  </div>
</div>

<div class="modal fade modal-constraint modal-events constraint_form" tabindex="-1" role="dialog">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      <h4 class="modal-title">Ajouter une contrainte</h4>
    </div>
    <div class="modal-body">
        <%= render 'constraints/form', locals: {planning: @planning, slot: @slot} %>
    </div>
  </div>
</div>

<div class="modal fade modal-update-constraint modal-events" tabindex="-1" role="dialog">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      <h4 class="modal-title">Modifier une contrainte</h4>
    </div>
    <div class="modal-body">
        <%= render 'constraints/form' %>
    </div>
  </div>
</div>

<div class="modal fade modal-update-profile-picture modal-events" tabindex="-1" role="dialog">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      <h4 class="modal-title">Modifier la photo</h4>
    </div>
    <div class="modal-body">
        <%= render 'users/form_profile_picture', resource: @user %>
    </div>
  </div>
</div>

<div class="row user_details">

    <div class="col-xs-4">
      <ul class="list-group">
        <li class="list-group-item justify-content-between">
          <div class="col-xs-8">
            <%= @user.email %> <br>
          </div>
          <div class="col-xs-4">
              <span class="fa fa-pencil modify-profile pointer" data-input="user_email"></span>
          </div>
          <br>
        </li>
        <li class="list-group-item justify-content-between">
          +33 6 89 90 95 26<br>
        </li>
        <li class="list-group-item justify-content-between">
          <div class="col-xs-4">
            Contrat :
          </div>
          <div class="col-xs-4">
            <span class="badge badge-default badge-pill"><%= @user.working_hours %>h/semaine</span>
          </div>
          <% if current_user.is_owner %>
            <div class="col-xs-4">
              <span class="fa fa-pencil modify-profile pointer" data-input="user_working_hours"></span>
            </div>
          <% end %>
          <br>
        </li>
      </ul>
    </div>

    <div class="col-xs-4">

      <li class="list-group-item justify-content-between">
        Jours de congés en cours de validation :
        <span class="badge badge-default badge-orange">25</span>
      </li>
      <li class="list-group-item justify-content-between">
        Jours de congés pris
        <span class="badge badge-default badge-pill">25</span>
      </li>
    </div>

    <div class="col-xs-4">
      <li class="list-group-item justify-content-between">
        Dernière connexion :
        <span class="badge badge-default badge-pill">
        <% unless @user.last_sign_in_at.nil? %>
          <%= @user.last_sign_in_at.strftime("%D %R") %>
        <% else %>
          Ne s'est jamais connecté
        <% end %>
        </span>
      </li>
    </div>

</div>

<div class="row">
</div>

app/views/users/_userinfo.html.erb
<h1>Infos générales</h1>


<ul>
  <li>
    <%= @user.email %>
  </li>
  <li>
    <%= @user.working_hours %>h/week
  </li>
  <li>
    <% @user.roles.each do |role| %>
    <button class="btn" style="margin: 5px; border-color: grey; background-color: <%= role.role_color %>; border-radius: 6px;"> <%= role.name %> </button>
    <% end %>
  </li>
</ul>

app/views/users/index.html.erb
<div class="new-invite">
    <%= link_to_if current_user.is_owner?, "Inviter un nouvel employé", new_user_path, class:"btn-primary btn-nav" %>
</div>
<div class="row equal">
  <% @users.each do |user| %>
      <div class="col-xs-12 col-sm-6 col-md-3 equal">
        <div class="users-card-list" style="<%= "opacity: 0.5" if user.invitation_accepted_at.nil?%>" >
          <div class="invitation-status <%= invitation_status(user) %>">
            <div class="status ">
              <% if user.invitation_sent_at.nil? %>
                employé non invité
              <% elsif user.invitation_accepted_at %>
                confirmé le <%= l user.invitation_accepted_at, format: :default_heure %>
              <% else %>
                invité le <%= l user.invitation_sent_at, format: :default_heure %>
              <% end %>
            </div>
            <div class="invite-link <%= "hide" if user.invitation_accepted_at %>">
              <%= link_to "Réinviter", user_reinvite_path(user) %>
            </div>
          </div>
          <div class="content">
            <%= link_to "" ,user_path(user), class:"link" %>
            <div class="title">
              <div class="name">
                <h2><%= "#{user.first_name&.capitalize} #{user.last_name&.capitalize}" %></h2>
                <p>
                  <%= user.email[0, user.email.index('@')]%><wbr><%= user.email[user.email.index('@'), (user.email.length + 1)]%>
                </p>
                <p> user.phone</p>
              </div>
              <%= profile_picture(user) %>
            </div>
            <div class="details">
              <div class="time-contract">
                <%= user.working_hours%>h/semaine
              </div>
              <div class="row">
                <% user.roles.each do |role| %>
                  <div class="col-xs-12 col-sm-6 col-md-6 role-tag" style="background-color: <%= role.color.hexadecimal_code %>; color: <%= role.color.dark?? "#f2f2f2" : "black" %>">
                    <%= role.name %>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
</div>

app/views/users/infos.html.erb
<%= render 'shared/usersteps', locals: {user: @user} %>
<h1>User key information</h1>

<ul>
    <%= @user.email %> <br>
    Contract: <%= @user.working_hours %>h/week <br>
    Total days off (2017): 12 <br>
    Remaing: 25 <br>
    <% @user.roles.each do |role| %>
    <button class="btn" style="margin: 5px; border-color: grey; background-color: <%= role.color.hexadecimal_code %>; border-radius: 6px;"> <%= role.name %> </button>
    <% end %>
</ul>

app/views/users/new.html.erb
<h1>Inviter un nouvel employé</h1>
<br>

<div class="new-user-form">
  <%= simple_form_for(@user, html: { id: "role-id" }, url: users_invite_path, method: :post) do |f| %>
    <%= f.error_notification %>
    <%= f.input :first_name, placeholder: "Prénom", label: false %>
    <%= f.input :last_name, placeholder: "Nom", label: false %>
    <%= f.input :working_hours, placeholder:"Nombre d'heures hebdomadaires", label: false %>
    <%= f.input :email, placeholder: "Email", label: false %>
    <%= f.hidden_field :is_owner, value: false  %>
    <div class="row">

      <% @roles.each do |role|%>
        <div class="col-xs-3" id="select-role">
            <input id="<%= role.id %>" class="role-checkbox" type="checkbox", name="user[role_ids][]" value="<%= role.id %>"/>
            <label for="<%= role.id %>"><%= role.name.capitalize %></label>
        </div>
      <% end %>
    </div>
    <%= f.input :profile_picture, as: :attachinary, label: false, placeholder: "Choose a profile picture" %>

    <div class="btn-group">
      <%= f.submit "Valider", class: "btn-primary btn-nav" %>
      <%= link_to 'Back', users_path, class: "btn-primary btn-nav"  %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<br>
<div class="row mb">
  <div class="col-xs-2 edit-profile-picture pointer">
    <%= avatar_with_border_color(@user) %>
  </div>
  <div class="col-xs-8 name">
    <ul class="list-inline" style="text-align:left">
      <li><h1> <%= @user.first_name&.capitalize %> </h1></li>
      <li><span class="fa fa-pencil modify-profile pointer" data-input="user_first_name"></span></li>
    </ul>

    <ul class="list-inline" style="text-align:left">
      <li><h1> <%= @user.last_name&.capitalize %></h1></li>
      <li><span class="fa fa-pencil modify-profile pointer" data-input="user_last_name"></span></li>
    </ul>
  </div>
  <div class="col-xs-2">
    <%= link_to "Add to calendar", ical_plannings_url(protocol: :webcal, format: :ics, key: "#{@user.key}"), class:"mybtn mybtn-medium"%>
  </div>
</div>
<%= render "user_infos" %>
<%= render "html_constraints_cal" %>