config/routes.rb
# == Route Map
#
#                               Prefix Verb   URI Pattern                                                        Controller#Action
#                          attachinary        /attachinary                                                       Attachinary::Engine
#                     new_user_session GET    /users/sign_in(.:format)                                           devise/sessions#new
#                         user_session POST   /users/sign_in(.:format)                                           devise/sessions#create
#                 destroy_user_session DELETE /users/sign_out(.:format)                                          devise/sessions#destroy
#                    new_user_password GET    /users/password/new(.:format)                                      devise/passwords#new
#                   edit_user_password GET    /users/password/edit(.:format)                                     devise/passwords#edit
#                        user_password PATCH  /users/password(.:format)                                          devise/passwords#update
#                                      PUT    /users/password(.:format)                                          devise/passwords#update
#                                      POST   /users/password(.:format)                                          devise/passwords#create
#             cancel_user_registration GET    /users/cancel(.:format)                                            devise_invitable/registrations#cancel
#                new_user_registration GET    /users/sign_up(.:format)                                           devise_invitable/registrations#new
#               edit_user_registration GET    /users/edit(.:format)                                              devise_invitable/registrations#edit
#                    user_registration PATCH  /users(.:format)                                                   devise_invitable/registrations#update
#                                      PUT    /users(.:format)                                                   devise_invitable/registrations#update
#                                      DELETE /users(.:format)                                                   devise_invitable/registrations#destroy
#                                      POST   /users(.:format)                                                   devise_invitable/registrations#create
#               accept_user_invitation GET    /users/invitation/accept(.:format)                                 devise/invitations#edit
#               remove_user_invitation GET    /users/invitation/remove(.:format)                                 devise/invitations#destroy
#                  new_user_invitation GET    /users/invitation/new(.:format)                                    devise/invitations#new
#                      user_invitation PATCH  /users/invitation(.:format)                                        devise/invitations#update
#                                      PUT    /users/invitation(.:format)                                        devise/invitations#update
#                                      POST   /users/invitation(.:format)                                        devise/invitations#create
#                                 root GET    /                                                                  pages#home
#                       planning_slots POST   /plannings/:planning_id/slots(.:format)                            slots#create
#                    new_planning_slot GET    /plannings/:planning_id/slots/new(.:format)                        slots#new
#                   edit_planning_slot GET    /plannings/:planning_id/slots/:id/edit(.:format)                   slots#edit
#                        planning_slot GET    /plannings/:planning_id/slots/:id(.:format)                        slots#show
#                                      PATCH  /plannings/:planning_id/slots/:id(.:format)                        slots#update
#                                      PUT    /plannings/:planning_id/slots/:id(.:format)                        slots#update
#                                      DELETE /plannings/:planning_id/slots/:id(.:format)                        slots#destroy
#           planning_compute_solutions GET    /plannings/:planning_id/compute_solutions(.:format)                compute_solutions#index
#                                      POST   /plannings/:planning_id/compute_solutions(.:format)                compute_solutions#create
# change_effectivity_planning_solution GET    /plannings/:planning_id/solutions/:id/change_effectivity(.:format) solutions#change_effectivity
#                    planning_solution GET    /plannings/:planning_id/solutions/:id(.:format)                    solutions#show
#                      events_planning GET    /plannings/:id/events(.:format)                                    plannings#events
#                resultevents_planning GET    /plannings/:id/resultevents(.:format)                              plannings#resultevents
#                            plannings GET    /plannings(.:format)                                               plannings#index
#                                      POST   /plannings(.:format)                                               plannings#create
#                             planning GET    /plannings/:id(.:format)                                           plannings#show
#                                      PATCH  /plannings/:id(.:format)                                           plannings#update
#                                      PUT    /plannings/:id(.:format)                                           plannings#update
#                       planning_users GET    /plannings/:id/users(.:format)                                     plannings#users
#                    planning_skeleton GET    /plannings/:id/skeleton(.:format)                                  plannings#skeleton
#                   planning_conflicts GET    /plannings/:id/conflicts(.:format)                                 plannings#conflicts
#                                users GET    /users(.:format)                                                   users#index
#                                 user GET    /users/:id(.:format)                                               users#show
#                                roles GET    /roles(.:format)                                                   roles#index
#                                      POST   /roles(.:format)                                                   roles#create
#                             new_role GET    /roles/new(.:format)                                               roles#new
#                           user_infos GET    /users/:id/infos(.:format)                                         users#infos
#                          user_dispos GET    /users/:id/dispos(.:format)                                        users#dispos
#                          sidekiq_web        /sidekiq                                                           Sidekiq::Web
#                    letter_opener_web        /letter_opener                                                     LetterOpenerWeb::Engine
#
# Routes for Attachinary::Engine:
#   cors GET  /cors(.:format) attachinary/cors#show {:format=>/json/}
#
# Routes for LetterOpenerWeb::Engine:
# clear_letters DELETE /clear(.:format)                 letter_opener_web/letters#clear
# delete_letter DELETE /:id(.:format)                   letter_opener_web/letters#destroy
#       letters GET    /                                letter_opener_web/letters#index
#        letter GET    /:id(/:style)(.:format)          letter_opener_web/letters#show
#               GET    /:id/attachments/:file(.:format) letter_opener_web/letters#attachment
#

Rails.application.routes.draw do

  mount Attachinary::Engine => "/attachinary"
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :plannings, only: [:show, :index, :update, :create] do
    collection do
      get '/ical', to: 'plannings#ical', as: 'ical'
    end
    resources :slots, only: [:create, :edit, :show, :update, :resolve, :new, :destroy]
    resources :compute_solutions, only: [:index, :create]
    resources :solution_slots, only: [:edit, :update]
    resources :solutions, only: [:show] do
      member do
        get :change_effectivity
      end
    end
    member do
      get :events, format: :json
      get :resultevents, format: :json
    end
  end

  get 'plannings/:id/users', to: 'plannings#users', as: 'planning_users'
  get 'plannings/:id/skeleton', to: 'plannings#skeleton', as: 'planning_skeleton'
  get 'plannings/:id/conflicts', to: 'plannings#conflicts', as: 'planning_conflicts'
  get 'plannings/:planning_id/compute_solution/:compute_solution_id', to: 'compute_solutions#show_calculation_details', as: 'show_cs_details'
  get 'plannings/:id/use_template/:planning_id', to: 'plannings#use_template', as: 'planning_use_template'


  resources :users, only: [:index, :show, :create, :new, :update] do
    resources :constraints, only: [:new, :create, :edit, :update, :destroy]
    resources :role_users, only: [:new, :create, :edit, :update, :destroy]
  end
  resources :roles, only: [:index, :new, :create, :show, :edit, :update, :destroy]
  resources :colors, only: [:new, :create]
  get 'users/:id/infos', to: 'users#infos', as: 'user_infos'
  get 'users/:id/personnal_constraints', to: 'users#personnal_constraints', as: 'user_personnal_constraints'
  post 'users/user_invite', to: 'users#user_invite', as: "users_invite"
  get 'users/:id/reinvite', to: 'users#reinvite', as: "user_reinvite"
  get 'users/:id/personnal_c_and_wh', to: 'users#personnal_constraints_and_working_hours', as: "user_c_and_wh"
  resources :colors, only: [:new, :create]

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">

  <!-- Logo -->
  <div class="footer-item-left">
    <a href="/" class="footer-wagon-item footer-wagon-link">Ça <span class="color-word">Plan</span> Pour Moi</a>
  </div>

  <div class="footer-links">
    <a href="#"><i class="fa fa-instagram"></i></a>
    <a href="#"><i class="fa fa-facebook"></i></a>
    <a href="#"><i class="fa fa-twitter"></i></a>
    <a href="#"><i class="fa fa-linkedin"></i></a>
  </div>
</div>

app/views/shared/_home_signin.html.erb
<div class="container-fluid banner-container home-signin">
  <div class="row">
    <div class="col-xs-6 ">
     <header class="intro-header">


      <h1 class="text">Ça <span class="color-word">Plan</span> Pour Moi :</h1>
       <h2 class="text_2">« Fini les cauchemars
        <br>de planification ! »</h2>
        <div class="row">
          <div class="col-xs-12 col-md-7 margin">
            <%= simple_form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
            <%= f.input :email, label: false, required: false, placeholder: "Email" %>
            <%= f.input :password, label: false, required: false, placeholder: "Mot de passe" %>
            <%= f.input :remember_me, label: "Se souvenir de moi", as: :boolean if devise_mapping.rememberable? %>
            <%= f.button :submit, "Connexion", class: "form-actions btn-primary btn-home btn-block " %>
            <% end %>

            <%= render "devise/shared/links" %>
          </div>
        </div>


      </header>
    </div>
    <div class="col-xs-12 col-md-6">
     <%= image_tag("background_picture.png", :alt => "planning_ex", class: "image_landing") %>
   </div>
 </div>
</div>

<section class="content-section-0">

  <div class="container">

    <div class="row center">
      <div class="col-xs-offset-4 col-xs-4 lead">
        <%= image_tag "logo-hr.png", alt: "Mon image", width: 150, height: 150 %>
      </div>
      <div class="col-xs-offset-2 col-xs-8">
        <div class="clearfix"></div>

        <p class="lead"><b>Ça <span class="color-word">plan</span> pour moi automatise la création de vos plannings.</b>
          <br>Laissez tomber les tableaux excel ou papier,
          <br>la planification deviendra un jeu d'enfant !
        <!--   <br>Ca plan pour moi vous permet de créer un planning qui convient à toute votre équipe en un clin d’oeil.</p> -->
        </div>
      </div>

    </div>
  </section>

  <div class="container background-container">
    <div class="row">



    <div class="col-xs-12 col-sm-6 col-md-3">
        <section class="content-section-a">
         <%= image_tag "wrench.png", alt: "Mon image", width: 150, height: 150 %>

         <div class="clearfix"></div>
         <h2 class="section-heading"><span class="color-word">1</span></h2>
         <p class="lead-etape"><b>Créez la structure de votre planning</b></p>
       </section>
     </div>

     <div class="col-xs-12 col-sm-6 col-md-3">
      <section class="content-section-a">
       <%= image_tag "worker.png", alt: "Mon image", width: 150, height: 150 %>

       <div class="clearfix"></div>
       <h2 class="section-heading"><span class="color-word">2</span></h2>
       <p class="lead-etape"><b>Assignez les collaborateurs dont vous avez besoin.</b></p>
     </section>
   </div>

   <div class="col-xs-12 col-sm-6 col-md-3">
    <section class="content-section-a">
     <%= image_tag "clipboard.png", alt: "Mon image", width: 150, height: 150 %>

     <div class="clearfix"></div>
     <h2 class="section-heading"><span class="color-word">3</span></h2>
     <p class="lead-etape"><b>Vos collaborateurs rentrent leurs disponibiltés.</b></p>
   </section>
 </div>

 <div class="col-xs-12 col-sm-6 col-md-3">
  <section class="content-section-a">
   <%= image_tag "checked.png", alt: "Mon image", width: 150, height: 150 %>

   <div class="clearfix"></div>
   <h2 class="section-heading"><span class="color-word">4</span></h2>
   <p class="lead-etape"><b>Ça plan pour moi s’occupe de créer votre planning.</b></p>
 </section>
</div>

</div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->

 <a href="/" class="navbar-wagon-brand navbar-wagon-item">
   <%= image_tag "logo-lr.png", alt: "Logo Ca Plane Pour Moi"%>
 </a>


 <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <% if user_signed_in? %>
      <!-- Avatar with dropdown menu -->
      <% if current_user.is_owner? %>
        <%= link_to statistics_algo_path do  %>
          <button class="btn-primary btn-nav mr-">
            <i class="fa fa-bar-chart"></i> <%= t("navbar.statistics", default: "Statitics") %>
          </button>
        <% end %>
        <%= link_to users_path do %>
          <button class="btn-primary btn-nav">
            <i class="fa fa-users"></i>  <%= t("navbar.users", default: "Users") %>
          </button>
        <% end %>
      <% end %>
        <div class="navbar-wagon-item">
          <div class="dropdown">
            <% if current_user.profile_picture? %>
              <%= cl_image_tag current_user.profile_picture.path, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
            <% else %>
              <%= image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
            <% end %>
            <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
              <li>
                <%= link_to plannings_path do %>
                  <i class="fa fa-home"></i>  <%= t("navbar.homepage", default: "Home") %>
                <% end %>
              </li>
              <li>
                <%= link_to user_path(current_user)  do %>
                  <i class="fa fa-user"></i> <%= t("navbar.profile", default: "Profil") %>
                <% end %>
              </li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete do %>
                  <i class="fa fa-sign-out"></i>  <%= t("navbar.sign_out", default: "Log out") %>
                <% end %>
              </li>
            </ul>
          </div>
        </div>
      <% else %>
      <!-- Login link (when logged out) -->

      <div>
        <%= link_to t(".sign_up", default: "S'inscrire"), new_user_registration_path, class: "form-actions btn-primary btn-nav btn-block" %>
      </div>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <% if user_signed_in? && current_user.profile_picture?   %>
              <%= cl_image_tag current_user.profile_picture.path, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
            <% else %>
              <%= image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
            <% end %>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <% if user_signed_in? %>
          <li>
            <%= link_to plannings_path do %>
              <i class="fa fa-home"></i>  <%= t("navbar.homepage", default: "Home") %>
            <% end %>
          </li>
          <li>
            <%= link_to user_path(current_user)  do %>
              <i class="fa fa-user"></i> <%= t("navbar.profile", default: "Profile") %>
            <% end %>
          </li>
          <% if current_user.is_owner? %>
            <li>
              <%= link_to users_path do %>
                <i class="fa fa-users"></i>  <%= t("navbar.users", default: "Users") %>
              <% end %>
            </li>
            <li>
              <%= link_to statistics_algo_path do %>
                <i class="fa fa-bar-chart"></i> <%= t("navbar.statistics", default: "Statitics") %>
              <% end %>
            </li>
          <% end %>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
              <i class="fa fa-sign-out"></i>  <%= t("navbar.sign_out", default: "Log out") %>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_planningsteps.html.erb
<div class="wrap-week-tag">
  <div class="week-tag <%= planning_slide_class(@planning) %>" >
      <p>S<%= @planning.week_number %></p>
  </div>
</div>

<% set_step_status %>
<div class="row" style="margin:0">
  <div class="steps">
    <div class="col-xs-2 step <%= @set_status1 %>">
      <div class="progress"><div class="progress-bar"></div></div>
      <div class="flex-col flex-col--center">
        <%= link_to "", planning_skeleton_path(@planning), {class: "dot un", 'data-toggle': "tooltip", title:"Faire le squelette de votre planning"}  %>
        <div class="comment text-center">Orga</div>
        <div class="triangle hide"></div>
      </div>
    </div>
    <div class="col-xs-2 step <%= @set_status2 %>">
      <div class="progress"><div class="progress-bar"></div></div>
      <div class="flex-col flex-col--center">
        <%= link_to "", planning_users_path(@planning), {class: "dot deux", 'data-toggle': "tooltip", title:"Constituer l'équipe de la semaine"} %>
        <div class="comment text-center">Equipe</div>
        <div class="triangle hide"></div>
      </div>
    </div>
      <div class="col-xs-2 step <%= @set_status3 %>">
      <div class="progress"><div class="progress-bar"></div></div>
      <div class="flex-col flex-col--center">
        <%= link_to "", planning_compute_solutions_path(@planning), {class: "dot trois", 'data-toggle': "tooltip", title:"Analyser les solutions proposées par CPPM"}  %>
        <div class="comment text-center">Solutions</div>
        <div class="triangle hide"></div>
      </div>
    </div>
    <div class="col-xs-2 step <%= @set_status4 %>">
      <div class="progress"><div class="progress-bar"></div></div>
      <div class="flex-col flex-col--center">
        <%= link_to "", planning_conflicts_path(@planning, solution_id: @solution), {class: "dot quatre", 'data-toggle': "tooltip", title:"Voir le Planning"} %>
        <div class="comment text-center">Planning</div>
        <div class="triangle hide"></div>
      </div>
    </div>
  </div>
  <div class="col-xs-4">
      <%= @button_link %>
  </div>

</div>



<%= content_for(:after_js) do %>
<script>
  $(".active > > .triangle").removeClass('hide')
  $(".active > > .triangle").addClass('show')
</script>
<% end %>

app/views/shared/_usersteps.html.erb
<!-- TODO : display de la meme manière que 'planning steps' -->
<div class="row">
  <div class="col-xs-12">
    <div class="planning-steps">
      <ul class="nav nav-tabs nav-justified">
        <li class="nav-item" onclick="showinfos">
          <a class="nav-link active" href="#">
          <div  style="color: light_grey; text-align: center; border-color: $mygrey; border-radius:50%;"><br>
            </div>
          </a>
        </li>
        <li>
          <a class="nav-link active" onclick="showdispos" href="#">
            <div  style="color: light_grey; text-align: center;""><br>
            </div>
          </a>
        </li>
      </ul>
    </div>
  </div>
</div>

<%= content_for(:after_js) do %>
<script>
function showinfos() {
  $('.infos').show();
  $('.dispos').hide();
};
function showdispos() {
  $('.dispos').show();
  $('.infos').hide();
};
</script>
<% end %>