config/routes.rb
#                               Prefix Verb   URI Pattern                                                        Controller#Action
#                          attachinary        /attachinary                                                       Attachinary::Engine
#                     new_user_session GET    /users/sign_in(.:format)                                           devise/sessions#new
#                         user_session POST   /users/sign_in(.:format)                                           devise/sessions#create
#                 destroy_user_session DELETE /users/sign_out(.:format)                                          devise/sessions#destroy
#                    new_user_password GET    /users/password/new(.:format)                                      devise/passwords#new
#                   edit_user_password GET    /users/password/edit(.:format)                                     devise/passwords#edit
#                        user_password PATCH  /users/password(.:format)                                          devise/passwords#update
#                                      PUT    /users/password(.:format)                                          devise/passwords#update
#                                      POST   /users/password(.:format)                                          devise/passwords#create
#             cancel_user_registration GET    /users/cancel(.:format)                                            devise_invitable/registrations#cancel
#                new_user_registration GET    /users/sign_up(.:format)                                           devise_invitable/registrations#new
#               edit_user_registration GET    /users/edit(.:format)                                              devise_invitable/registrations#edit
#                    user_registration PATCH  /users(.:format)                                                   devise_invitable/registrations#update
#                                      PUT    /users(.:format)                                                   devise_invitable/registrations#update
#                                      DELETE /users(.:format)                                                   devise_invitable/registrations#destroy
#                                      POST   /users(.:format)                                                   devise_invitable/registrations#create
#               accept_user_invitation GET    /users/invitation/accept(.:format)                                 devise/invitations#edit
#               remove_user_invitation GET    /users/invitation/remove(.:format)                                 devise/invitations#destroy
#                  new_user_invitation GET    /users/invitation/new(.:format)                                    devise/invitations#new
#                      user_invitation PATCH  /users/invitation(.:format)                                        devise/invitations#update
#                                      PUT    /users/invitation(.:format)                                        devise/invitations#update
#                                      POST   /users/invitation(.:format)                                        devise/invitations#create
#                                 root GET    /                                                                  pages#home
#                       planning_slots POST   /plannings/:planning_id/slots(.:format)                            slots#create
#                    new_planning_slot GET    /plannings/:planning_id/slots/new(.:format)                        slots#new
#                   edit_planning_slot GET    /plannings/:planning_id/slots/:id/edit(.:format)                   slots#edit
#                        planning_slot GET    /plannings/:planning_id/slots/:id(.:format)                        slots#show
#                                      PATCH  /plannings/:planning_id/slots/:id(.:format)                        slots#update
#                                      PUT    /plannings/:planning_id/slots/:id(.:format)                        slots#update
#                                      DELETE /plannings/:planning_id/slots/:id(.:format)                        slots#destroy
#           planning_compute_solutions GET    /plannings/:planning_id/compute_solutions(.:format)                compute_solutions#index
#                                      POST   /plannings/:planning_id/compute_solutions(.:format)                compute_solutions#create
# change_effectivity_planning_solution GET    /plannings/:planning_id/solutions/:id/change_effectivity(.:format) solutions#change_effectivity
#                    planning_solution GET    /plannings/:planning_id/solutions/:id(.:format)                    solutions#show
#                      events_planning GET    /plannings/:id/events(.:format)                                    plannings#events
#                resultevents_planning GET    /plannings/:id/resultevents(.:format)                              plannings#resultevents
#                            plannings GET    /plannings(.:format)                                               plannings#index
#                                      POST   /plannings(.:format)                                               plannings#create
#                             planning GET    /plannings/:id(.:format)                                           plannings#show
#                                      PATCH  /plannings/:id(.:format)                                           plannings#update
#                                      PUT    /plannings/:id(.:format)                                           plannings#update
#                       planning_users GET    /plannings/:id/users(.:format)                                     plannings#users
#                    planning_skeleton GET    /plannings/:id/skeleton(.:format)                                  plannings#skeleton
#                   planning_conflicts GET    /plannings/:id/conflicts(.:format)                                 plannings#conflicts
#                                users GET    /users(.:format)                                                   users#index
#                                 user GET    /users/:id(.:format)                                               users#show
#                                roles GET    /roles(.:format)                                                   roles#index
#                                      POST   /roles(.:format)                                                   roles#create
#                             new_role GET    /roles/new(.:format)                                               roles#new
#                           user_infos GET    /users/:id/infos(.:format)                                         users#infos
#                          user_dispos GET    /users/:id/dispos(.:format)                                        users#dispos
#                          sidekiq_web        /sidekiq                                                           Sidekiq::Web
#                    letter_opener_web        /letter_opener                                                     LetterOpenerWeb::Engine
#
# Routes for Attachinary::Engine:
#   cors GET  /cors(.:format) attachinary/cors#show {:format=>/json/}
#
# Routes for LetterOpenerWeb::Engine:
# clear_letters DELETE /clear(.:format)                 letter_opener_web/letters#clear
# delete_letter DELETE /:id(.:format)                   letter_opener_web/letters#destroy
#       letters GET    /                                letter_opener_web/letters#index
#        letter GET    /:id(/:style)(.:format)          letter_opener_web/letters#show
#               GET    /:id/attachments/:file(.:format) letter_opener_web/letters#attachment
#

Rails.application.routes.draw do

  mount Attachinary::Engine => "/attachinary"
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :plannings, only: [:show, :index, :update, :create] do
    collection do
      get '/ical', to: 'plannings#ical', as: 'ical'
    end
    resources :slots, only: [:create, :edit, :show, :update, :resolve, :new, :destroy]
    resources :compute_solutions, only: [:index, :create]
    resources :solution_slots, only: [:edit, :update]
    resources :solutions, only: [:show] do
      member do
        get :change_effectivity
      end
    end
    member do
      get :events, format: :json
      get :resultevents, format: :json
    end
  end

  get 'plannings/:id/users', to: 'plannings#users', as: 'planning_users'
  get 'plannings/:id/skeleton', to: 'plannings#skeleton', as: 'planning_skeleton'
  get 'plannings/:id/conflicts', to: 'plannings#conflicts', as: 'planning_conflicts'
  get 'plannings/:planning_id/compute_solution/:compute_solution_id', to: 'compute_solutions#show_calculation_details', as: 'show_cs_details'
  get 'plannings/:id/use_template/:planning_id', to: 'plannings#use_template', as: 'planning_use_template'


  resources :users, only: [:index, :show, :create, :new, :update] do
    resources :constraints, only: [:new, :create, :edit, :update, :destroy]
    resources :role_users, only: [:new, :create, :edit, :update, :destroy]
  end
  resources :roles, only: [:index, :new, :create, :show, :edit, :update, :destroy]
  resources :colors, only: [:new, :create]
  get 'users/:id/infos', to: 'users#infos', as: 'user_infos'
  get 'users/:id/personnal_constraints', to: 'users#personnal_constraints', as: 'user_personnal_constraints'
  post 'users/user_invite', to: 'users#user_invite', as: "users_invite"
  get 'users/:id/reinvite', to: 'users#reinvite', as: "user_reinvite"
  get 'users/:id/personnal_c_and_wh', to: 'users#personnal_constraints_and_working_hours', as: "user_c_and_wh"
  resources :colors, only: [:new, :create]

  get 'statistics_algo', to: 'algo_stats#show_statistics_algo', as: 'statistics_algo'

app/helpers/planning_helper.rb
module PlanningHelper
  def planning_slide_class(planning)
    planning.status
  end

  def planning_slide_label(week_number)
    "S#{week_number}"
  end

  def planning_status_label(planning)
    case planning.status.to_sym
    when :not_started
      '(Aucun Planning)'
    when :in_progress
      '(En cours)'
    when :complete
      '(Validé)'
    else
      '(Incomplet)'
    end
  end

  def planning_link(planning, week_number)
    if planning.nil?
      link_to planning_slide_label(week_number), plannings_path(alert: "Planning pas fini, Allez grouille toi patron")
    else
      if current_user.is_owner
        case planning.status.to_sym
          when :not_started, :in_progress
            link_to planning_slide_label(week_number), planning_skeleton_path(planning)
          else
          link_to planning_slide_label(week_number), planning_conflicts_path(planning)
        end
      elsif planning.chosen_solution.nil?
        link_to planning_slide_label(week_number), "#"
      else
        link_to planning_slide_label(week_number), planning_solution_path(id: planning.chosen_solution.id, planning_id: planning.id)
      end

    end
  end

  def parse_week_number(week_number, year_number)
    week_start = Date.commercial(year_number, week_number, 1).strftime('%d/%m')
    week_end = Date.commercial(year_number, week_number, 7).strftime('%d/%m')
    "Du #{week_start} au #{week_end}"
  end

  def planning_count_people_on_similar_slot(planning, slot)
    planning.slots.count do |s|
      s.start_at == slot.start_at &&
        s.end_at == slot.end_at &&
        s.role_id == slot.role_id
    end
  end

end

app/views/plannings/_use_template_form.html.erb
<%= simple_form_for [@planning] do |f| %>
  <%= f.error_notification %>
    <div class="row mr0 ml0">
      <% @plannings.each do |planning| %>
        <%= link_to planning_use_template_path(@planning, planning.id), method: :get do %>
          <div class="col-xs-3 pl- pr- mb">
            <div class="boxes <%= planning.status %>">
              <b><%= "S#{planning.week_number}" %></b>-<%= planning.year %><br>
              <%= planning_status_label(planning) %>
              <p><%= parse_week_number(planning.week_number, planning.year) %></p>
            </div>
          </div>
        <% end %>
      <% end  %>
    </div>
  <% end %>

app/views/plannings/conflicts.html.erb
<%= render 'shared/planningsteps', locals: {planning: @planning, url: @url, solution: @solution} %>

<div class="wrap-plan" >

  <div class="modal fade modal-reassignment" tabindex="-1" role="dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Slot - Autres possibilités d'affectation</h4>
      </div>
      <div class="modal-body">
      </div>
    </div>
  </div>

  <% unless @solution.nil? %>
    <div class="row">
      <div class="col-xs-12 col-sm-2 flex-col">
        <h3>Légende</h3>
        <div class="mb++">
          <% @roles.each do |role| %>
          <div class="role-tag text-center" style="background-color: <%= role.color.hexadecimal_code %>; color: <%= role.color.dark?? "#f2f2f2" : "black" %>">
            <%= role.name.capitalize %>
          </div>
          <% end %>
        </div>
      </div>
      <div class="col-xs-12 col-sm-10 le_calendrier">
        <div id = "calendar">
        </div>
      </div>
    </div>
  <% end %>

</div>


<!-- JS part not involving fullcalendar is in slots.js -->
<%= javascript_include_tag "components/calendar-conflicts" %>
<%= content_for(:after_js) do %>

  <script>
    var events = '<%= resultevents_planning_path(@planning.id, solution_id: @solution.id, format: :json) %>';
    var defaultDate = "<%= Date.commercial(@planning.year, @planning.week_number, 1).beginning_of_week %>";
    modifyCalendar(events, defaultDate);
  </script>
<% end %>

app/views/plannings/edit.html.erb
  <div class="row">
    <%= simple_form_for (@planning) do |f| %>
    <% @users.each do |user| %>

    <div class="col-xs-12 col-sm-4">

      <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://kitt.lewagon.com/placeholder/cities/shanghai');">

        <label >
          <input
          type="checkbox"
          name="planning[user_ids][]"
          value="<%= user.id %>"
          <%= @planning.users.include?(user) ? "checked" : "" %>
          />
          <%= user.first_name %>
          <br>
          <%= user.email %>
        </label>
      </div>
    </div>
    <% end %>
  </div>


<%= f.button :submit %>
<% end %>

app/views/plannings/ical.html.erb
<h1>Ical Planning <%= @user.first_name %></h1>
<div class="mb+" style="display:flex">

  <%= link_to "Add to calendar", ical_plannings_url(protocol: :webcal, format: :ics, key: "#{current_user.key}"), class:"mybtn mr+"%>
  <%= link_to "test", ical_plannings_url(key:   "#{current_user.key}"), class:"mybtn" %>
</div>
  <table class="table table-striped">
      <% @slots.each do |slot| %>
        <tr>
          <td>start: <%= slot.start_at %></td>
          <td>end: <%= slot.end_at %></td>
          <td>role: <%= slot.role.name %></td>
          <td>summary : <%= "#{slot.role.name} ##{slot.length / 3600}h" %></td>
        </tr>
      <% end %>

  </table>

app/views/plannings/index.html.erb
<div class="wraper">
  <h2>
    <i class="fa fa-calendar" aria-hidden="true"></i>  Plannings
  </h2>
  <div class="scrollbar">
    <div class="handle">
      <div class="mousearea"></div>
    </div>
  </div>
  <button class="backward"><i class="fa fa-chevron-left" aria-hidden="true"></i> </button>
  <button class="forward"><i class="fa fa-chevron-right" aria-hidden="true"></i> </button>
  <div id="planning-list" class="frame">
    <ul class="slidee">
      <% @plannings_list.each do |week| %>
        <li class="<%= week[:planning].nil?? "not_started" : planning_slide_class(week[:planning])  %>">
          <div class="date_range">
            <%= week[:year] %> <br>
            <%= parse_week_number(week[:week_number], week[:year]) %>
          </div>
          <p></p>
          <div class="premier-plan">
            <% if week[:planning].nil? && current_user.is_owner %>
            <%= link_to "S#{week[:week_number]}", plannings_path(year_number: week[:year], week_number: week[:week_number]), method: :post %>
            <% else %>
              <%= planning_link(week[:planning], week[:week_number]) %>
            <% end %>
          </div>
          <div><%= week[:planning].nil?? "(Aucun Planning)" : planning_status_label(week[:planning]) %></div>
        </li>
      <% end %>
    </ul>
  </div>

  <div class="row">
    <div class="col-xs-9">
      <h2>
        <i class="fa fa-users" aria-hidden="true"></i>  Ressources
      </h2>
      <ul class="user-list list-inline">
        <% if current_user.is_owner %>
          <li >
            <%= link_to new_user_path do  %>
              <div class="plus-avatar">
                <div class="plus-disc"></div>
                <i class="fa fa-plus" aria-hidden="true"></i>
              </div>
            <% end %>
          </li>
        <% end %>
        <% @users.each do |user| %>
        <li id="drag1" draggable="true" ondragstart="drag(event)" ondrop="" data-toggle="modal" data-target="#myModalHorizontal">
          <% unless (current_user.is_owner || user == current_user) %>
            <%= avatar_with_border_color(user) %>
            <p><%= user.first_name.capitalize%></p>
          <% else %>
            <%= link_to user_path(user), class: "show-user-link" do %>
                <%= avatar_with_border_color(user) %>
                <p><%= user.first_name.capitalize%></p>
            <% end %>
          <% end %>

        </li>
        <% end %>
      </ul>
    </div>
    <div class="col-xs-3">
      <h2>
        <i class="fa fa-suitcase" aria-hidden="true"></i> Métiers
      </h2>
      <div class="list-metiers">
        <%= link_to new_role_path, class: "create-role-link" do %>
          <div class="metier">
              <i class="fa fa-plus" aria-hidden="true"></i>
          </div>
        <% end %>
        <%  @roles.each do |role| %>
          <%= link_to edit_role_path(role.id), class: "edit-role-link" do %>
            <div class="metier" style="background-color: <%= role.color.hexadecimal_code%>; color: <%= role.color.dark?? "#f2f2f2" : "black" %>"> <%= role.name.capitalize %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div id="ModalEditRole"></div>
<div id="ModalCreateRole"></div>

<%= content_for(:after_js) do %>
  <script>

    var modalPosition = function(modal, position) {
      modal.style.setProperty('--postop', position -300 + "px");
      };

    $(".edit-role-link").on("click", function(event) {
      event.preventDefault();
      $.ajax({
        type: "GET",
        url: this.href
      });
    var modalContent = document.querySelector("#ModalEditRole");
    var Yposition = document.querySelector(".edit-role-link").getBoundingClientRect().y;
    // console.log(Yposition); // take position of 1st .edit-role-link
    modalPosition(modalContent, Yposition);
  });

    $(".create-role-link").on("click", function(event) {
      event.preventDefault();
      $.ajax({
        type: "GET",
        url: this.href
      });
      var modalContent = document.querySelector("#ModalCreateRole");
      var Yposition = document.querySelector(".create-role-link").getBoundingClientRect().y;
      // console.log(Yposition); // take position of 1st .edit-role-link
      modalPosition(modalContent, Yposition);
    });

  </script>
<% end %>

app/views/plannings/skeleton.html.erb
  <%= render 'shared/planningsteps', locals: {planning: @planning, url: @url} %>

  <div class="wrap-plan">

    <div class="modal fade modal-events slot_form" tabindex="-1" role="dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">Propriétés du créneau</h4>
        </div>
        <div class="modal-body">
            <%= render 'slots/form', locals: {planning: @planning, slot: @slot} %>
        </div>
      </div>
    </div>

    <div class="modal fade modal-use-template ui-draggable" tabindex="-1" role="dialog">
      <div class="modal-content this">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">Utiliser un template</h4>
        </div>
        <div class="modal-body pl pr">
            <%= render 'use_template_form' %>
        </div>
      </div>
    </div>


    <div class="row">
      <div class="col-xs-12 col-sm-2 flex-col">
        <h3>Légende</h3>
        <div class="mb++">
          <% @roles.each do |role| %>
          <div class="role-tag text-center" style="background-color: <%= role.color.hexadecimal_code %>; color: <%= role.color.dark?? "#f2f2f2" : "black" %>">
            <%= role.name.capitalize %>
          </div>
          <% end %>
        </div>
        <h3>Actions</h3>
        <button class="mybtn mybtn--small use_template">Dupliquer</button>
      </div>
      <div class="col-xs-12 col-sm-10 le_calendrier">
        <div id = "calendar">
        </div>
      </div>
    </div>

  </div>


<!-- JS part not involving fullcalendar is in slots.js -->
<%= javascript_include_tag "components/calendar" %>
<%= content_for(:after_js) do %>

  <script>
    var events = '<%= events_planning_path(@planning.id, format: :json) %>';
    var defaultDate = "<%= @planning.start_date %>";
    modifyCalendar(events, defaultDate);
  </script>
<% end %>

app/views/plannings/users.html.erb
<%= render 'shared/planningsteps', locals: {planning: @planning, url: @url} %>

<div class="wrap-plan" style="padding-top:40px; padding-right: 40px" >
  <div class="row">
    <div class="roles-decrement">
    </div>
  </div>

  <%= simple_form_for(@planning, html: { id: "user-submit-form"}) do |f| %>
    <div class="row equal">
      <% @users.each do |user| %>
        <div class="col-xs-6 col-sm-4 col-md-2 equal">
          <div class="users-card-list <%= @planning.users.include?(user) ? "checked" : "" %>" style="background-color: white" >
            <div class="content">
              <label style="text-align: left">
                <input class="checkbox user-select" type="checkbox" name="planning[user_ids][]" value="<%= user.id %>"<%= @planning.users.include?(user) ? "checked" : "" %>/>
                <div class="title">
                  <div class="name small">
                    <h2><%= "#{user.first_name&.capitalize} #{user.last_name&.capitalize}" %></h2>
                    <p><%= user.working_hours%>h/semaine</p>
                  </div>
                  <%= profile_picture(user, "small") %>
                </div>
                <div class="details">
                  <div class="row">
                    <% user.roles.each do |role| %>
                      <div class="col-xs-12 role-tag" style="background-color: <%= role.color.hexadecimal_code %>; color: <%= role.color.dark?? "#f2f2f2" : "black" %>">
                        <%= role.name %>
                      </div>
                    <% end %>
                  </div>
                </div>
              </label>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>



<%= content_for(:after_js) do %>
    <script>
        $("#user-submit-btn").click(function(event){
          event.preventDefault();
          document.getElementById("user-submit-form").submit();
        });
    </script>

<% end %>